name: Example Workflow

on: [push]

env:
  LAST_MAVEN_COMMAND: mvn clean install

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Print the global variable
        run: echo "Workflow-level variable $LAST_MAVEN_COMMAND"

      - name: Run maven command
        run: $LAST_MAVEN_COMMAND

      - name: github env var test
        run: echo "and the github env var is ${{ vars.TESTMAVENCMD}}"


